# Generated by Django 5.1.2 on 2024-10-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=255)),
                ('SImage', models.ImageField(upload_to='services/images/')),
            ],
        ),
    ]
