# Generated by Django 5.1.2 on 2024-10-18 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_catservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='catservices',
            name='serviceId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.service'),
        ),
    ]
